#version 460 core
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_ray_query: require

#define RAY_QUERY

#define VISIBLITY_IMAGE light_poly_visiblity
#define OUT_DIFFUSE_IMAGE   out_light_poly_diffuse
#define OUT_SPECULAR_IMAGE  out_light_poly_specular
#define LIGHT_DIVIDE 25.
#define VISIBLITY_KERNEL 2

//#define EXTREME_SPEEDUP 1

#define LIGHT_POLYGON 1
#define OUTPUTS RAY_LIGHT_DIRECT_POLY_OUTPUTS
#include "ray_light_poly_fast.glsl"
