#version 460 core
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_ray_query: require

#define RAY_QUERY

#define VISIBLITY_IMAGE light_point_visiblity
#define OUT_DIFFUSE_IMAGE   out_light_point_diffuse
#define OUT_SPECULAR_IMAGE  out_light_point_specular
#define LIGHT_DIVIDE 4.
#define VISIBLITY_KERNEL 3

#define LIGHT_POINT 1
#define OUTPUTS RAY_LIGHT_DIRECT_POINT_OUTPUTS
#include "ray_light_poly_fast.glsl"
