#version 460
#include "debug.glsl"
#include "utils.glsl"
#include "color_spaces.glsl"
#include "noise.glsl"
#include "brdf.glsl"

#define GLSL
#include "ray_interop.h"
#undef GLSL

#define DIELECTRIC_SPECULAR_MULTIPLIER 0.02 // default value from pbr papers, but 0.04 in Unreal Engine

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0, rgba16f) uniform image2D out_dest;

layout(set = 0, binding = 1, rgba8) uniform readonly image2D base_color_a;
layout(set = 0, binding = 2, rgba16f) uniform readonly image2D emissive;
layout(set = 0, binding = 3, rgba16f) uniform readonly image2D normals_gs;
layout(set = 0, binding = 4, rgba8) uniform readonly image2D material_rmxx;

layout(set = 0, binding = 5) uniform UBO { UniformBuffer ubo; } ubo;

layout(set = 0, binding = 6, rgba16f) uniform readonly image2D asvgf_direct_diffuse;
layout(set = 0, binding = 7, rgba16f) uniform readonly image2D asvgf_direct_specular;
layout(set = 0, binding = 8, rgba16f) uniform readonly image2D asvgf_indirect_specular;
layout(set = 0, binding = 9, rgba16f) uniform readonly image2D asvgf_indirect_diffuse;

layout(set = 0, binding = 10, rgba16f) uniform readonly image2D legacy_blend;
layout(set = 0, binding = 11, rgba16f) uniform readonly image2D final_atrous_flashlight_diffuse;
layout(set = 0, binding = 12, rgba16f) uniform readonly image2D final_atrous_flashlight_specular;
layout(set = 0, binding = 13, rgba16f) uniform readonly image2D final_atrous_direct_diffuse;
layout(set = 0, binding = 14, rgba16f) uniform readonly image2D final_atrous_direct_specular;
layout(set = 0, binding = 15, rgba16f) uniform readonly image2D final_atrous_indirect_specular;

//#define DEBUG_NOISE
#ifdef DEBUG_NOISE
layout(set = 0, binding = 29) uniform sampler3D blue_noise_texture;
#include "bluenoise.glsl"
#endif

// Blatantly copypasted from https://www.shadertoy.com/view/XsGfWV
vec3 aces_tonemap(vec3 color){
	mat3 m1 = mat3(
		0.59719, 0.07600, 0.02840,
		0.35458, 0.90834, 0.13383,
		0.04823, 0.01566, 0.83777
	);
	mat3 m2 = mat3(
		1.60475, -0.10208, -0.00327,
		-0.53108,  1.10813, -0.07276,
		-0.07367, -0.00605,  1.07602
	);
	vec3 v = m1 * color;
	vec3 a = v * (v + 0.0245786) - 0.000090537;
	vec3 b = v * (0.983729 * v + 0.4329510) + 0.238081;
	//return pow(clamp(m2 * (a / b), 0.0, 1.0), vec3(1.0 / 2.2));
	return clamp(m2 * (a / b), 0.0, 1.0);
}

vec3 reinhard(vec3 color){
	return color / (color + 1.0);
}

vec3 reinhard02(vec3 c, vec3 Cwhite2) {
	return c * (1. + c / Cwhite2) / (1. + c);
}

float normpdf2(in float x2, in float sigma) { return 0.39894*exp(-0.5*x2/(sigma*sigma))/sigma; }
float normpdf(in float x, in float sigma) { return normpdf2(x*x, sigma); }

void readNormals(ivec2 uv, out vec3 geometry_normal, out vec3 shading_normal) {
	const vec4 n = imageLoad(normals_gs, uv);
	geometry_normal = normalDecode(n.xy);
	shading_normal = normalDecode(n.zw);
}

vec3 restoreSpecular(vec3 decolorized_specular, vec3 base_color, float metalness) {
	const vec3 plasticSpecular = decolorized_specular * DIELECTRIC_SPECULAR_MULTIPLIER;
	const vec3 metalSpecular = decolorized_specular * base_color;
	return mix(plasticSpecular, metalSpecular, metalness);
}

void main() {
	const ivec2 res = ubo.ubo.res;
	const ivec2 pix = ivec2(gl_GlobalInvocationID);

	if (any(greaterThanEqual(pix, res))) {
		return;
	}

	const vec3 base_color = SRGBtoLINEAR(imageLoad(base_color_a, pix).rgb);
	const float metalness = imageLoad(material_rmxx, pix).g;
	const bool separated_reflection = (ubo.ubo.renderer_flags & RENDERER_FLAG_SEPARATED_REFLECTION) != 0;

	vec3 geometry_normal, shading_normal;
	readNormals(pix, geometry_normal, shading_normal);

	if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_DISABLED) {
		// no-op, just continue
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_BASECOLOR) {
		imageStore(out_dest, pix, vec4(LINEARtoSRGB(imageLoad(base_color_a, pix).rgb), 0.0));
		return;
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_BASEALPHA) {
		imageStore(out_dest, pix, imageLoad(base_color_a, pix).aaaa);
		return;
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_EMISSIVE) {
		imageStore(out_dest, pix, vec4(LINEARtoSRGB(imageLoad(emissive, pix).rgb), 0.0));
		return;
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_MATERIAL) {
		imageStore(out_dest, pix, vec4(imageLoad(material_rmxx, pix).rg, 0.0, 0.0));
		return;
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_NSHADE) {
		imageStore(out_dest, pix, vec4(0.5 + shading_normal * 0.5, 0.0));
		return;
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_NGEOM) {
		imageStore(out_dest, pix, vec4(0.5 + geometry_normal * 0.5, 0.0));
		return;
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_CONFIDENCE) {
		vec2 confidence = vec2(imageLoad(final_atrous_direct_diffuse, pix).a, imageLoad(final_atrous_direct_specular, pix).a);
		float indirect_specular_confidence = imageLoad(final_atrous_indirect_specular, pix).a;
		imageStore(out_dest, pix, vec4(confidence.x, confidence.y, indirect_specular_confidence, 0.0));
		return;
	}

#ifdef DEBUG_NOISE
	imageStore(out_dest, pix, blueNoise(ivec3(pix.xy, ubo.ubo.frame_counter)));
	return;
#endif

	const vec4 asvgf_direct_diffuse_sample = imageLoad(asvgf_direct_diffuse, pix);
	const vec4 asvgf_direct_specular_sample = imageLoad(asvgf_direct_specular, pix);
	const vec4 asvgf_indirect_specular_sample = imageLoad(asvgf_indirect_specular, pix);
	const vec4 asvgf_indirect_diffuse_sample = imageLoad(asvgf_indirect_diffuse, pix);
	const vec3 flashlight_diffuse = imageLoad(final_atrous_flashlight_diffuse, pix).rgb;
	const vec3 flashlight_specular = imageLoad(final_atrous_flashlight_specular, pix).rgb;

	vec3 direct_diffuse = asvgf_direct_diffuse_sample.rgb;
	vec3 indirect_diffuse = asvgf_indirect_diffuse_sample.rgb;
	vec3 direct_specular = asvgf_direct_specular_sample.rgb;
	vec3 indirect_specular = asvgf_indirect_specular_sample.rgb;

	vec3 diffuse = direct_diffuse + indirect_diffuse;
	vec3 indirect_specular_colored = separated_reflection ? restoreSpecular(indirect_specular, base_color, metalness) : indirect_specular;
	vec3 specular = direct_specular + indirect_specular_colored;

	if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_DISABLED) {
		// Skip
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_DIRECT) {
		imageStore(out_dest, pix, vec4(LINEARtoSRGB(direct_diffuse + direct_specular + flashlight_diffuse + flashlight_specular), 0.0));
		return;
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_DIRECT_DIFF) {
		imageStore(out_dest, pix, vec4(LINEARtoSRGB(direct_diffuse + flashlight_diffuse), 0.0));
		return;
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_DIRECT_SPEC) {
		imageStore(out_dest, pix, vec4(LINEARtoSRGB(direct_specular + flashlight_specular), 0.0));
		return;
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_INDIRECT) {
		imageStore(out_dest, pix, vec4(LINEARtoSRGB(indirect_diffuse + indirect_specular), 0.0));
		return;
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_INDIRECT_SPEC) {
		imageStore(out_dest, pix, vec4(LINEARtoSRGB(indirect_specular), 0.0));
		return;
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_INDIRECT_DIFF) {
		imageStore(out_dest, pix, vec4(LINEARtoSRGB(indirect_diffuse), 0.0));
		return;
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_DIFFUSE) {
		imageStore(out_dest, pix, vec4(LINEARtoSRGB(indirect_diffuse + direct_diffuse + flashlight_diffuse), 0.0));
		return;
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_SPECULAR) {
		imageStore(out_dest, pix, vec4(LINEARtoSRGB(indirect_specular + direct_specular + flashlight_specular), 0.0));
		return;
	}

#ifdef DEBUG_VALIDATE_EXTRA
	if (IS_INVALIDV(diffuse)) {
		debugPrintfEXT("pix=(%d,%d) diffuse=inv", pix.x, pix.y);
		diffuse = vec3(0.0);
	}

	if (IS_INVALIDV(specular)) {
		debugPrintfEXT("pix=(%d,%d) specular=inv, specular=(%f, %f, %f)",
			pix.x, pix.y,
			specular.r, specular.g, specular.b);
		specular = vec3(0.0);
	}
#endif

	DEBUG_VALIDATE_RANGE_VEC3("denoiser.diffuse", diffuse, 0.0, 1e6);
	DEBUG_VALIDATE_RANGE_VEC3("denoiser.specular", specular, 0.0, 1e6);

	diffuse += flashlight_diffuse;
	specular += flashlight_specular;

	vec3 colour = vec3(0.0);

	if (ubo.ubo.debug_display_only != DEBUG_DISPLAY_LIGHTING) {
		colour = mixFinalColor(base_color, diffuse, specular, metalness);
	} else {
		colour = diffuse + specular;
	}

	const vec4 legacy_blend_sample = imageLoad(legacy_blend, pix);

	colour += imageLoad(emissive, pix).rgb;
	// Revealage. TODO: which colorspace?
	colour *= legacy_blend_sample.a;

	colour = LINEARtoSRGB(colour);

// See issue https://github.com/w23/xash3d-fwgs/issues/668, map test_blendmode_additive_alpha.
// Adding emissive_blend to the final color in the incorrect sRGB space. It makes
// it look much more like the original. Adding emissive in the *correct* linear space differs
// from the original a lot, and looks perceptively worse.
	colour += legacy_blend_sample.rgb;

	DEBUG_VALIDATE_RANGE_VEC3("denoiser.colour", colour, 0.0, 1e6);

	imageStore(out_dest, pix, vec4(colour, 0.0/*unused*/));
}
