#version 460 core
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_ray_query: require

#define GLSL
#include "ray_interop.h"
#undef GLSL

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 1) uniform accelerationStructureEXT tlas;
layout(set = 0, binding = 2) uniform UBO { UniformBuffer ubo; } ubo;

layout(set = 0, binding = 6) uniform sampler2D textures[MAX_TEXTURES];

layout (set = 0, binding = 7) readonly buffer SBOLights { LightsMetadata m; } lights;
layout (set = 0, binding = 8, align = 1) readonly buffer UBOLightClusters {
	LightCluster clusters_[MAX_LIGHT_CLUSTERS];
} light_grid;

layout(set = 0, binding = 10, rgba32f) uniform readonly image2D position_t;
layout(set = 0, binding = 11, rgba16f) uniform readonly image2D normals_gs;
layout(set = 0, binding = 12, rgba8) uniform readonly image2D material_rmxx;
layout(set = 0, binding = 13, rgba8) uniform readonly image2D base_color_a;
layout(set = 0, binding = 14, rgba32f) uniform readonly image2D geometry_prev_position;
layout(set = 0, binding = 15, rgba32f) uniform readonly image2D reflection_direction_pdf;

layout(set = 0, binding = 20, rgba16f) uniform writeonly image2D out_light_poly_diffuse;
layout(set = 0, binding = 21, rgba16f) uniform writeonly image2D out_light_poly_specular;
layout(set = 0, binding = 22, rgba16f) uniform writeonly image2D out_temporal_light_poly_0;
layout(set = 0, binding = 23, rgba16f) uniform readonly image2D prev_temporal_light_poly_0;
layout(set = 0, binding = 24, rgba16f) uniform writeonly image2D out_temporal_light_poly_1;
layout(set = 0, binding = 25, rgba16f) uniform readonly image2D prev_temporal_light_poly_1;
layout(set = 0, binding = 26, rgba32f) uniform writeonly image2D out_temporal_light_poly_normal_roughness;
layout(set = 0, binding = 27, rgba32f) uniform readonly image2D prev_temporal_light_poly_normal_roughness;
layout(set = 0, binding = 28, rgba16f) uniform writeonly image2D out_light_polygon_confidence;
layout(set = 0, binding = 29, rgba16f) uniform writeonly image2D out_temporal_light_poly_2;
layout(set = 0, binding = 34, rgba16f) uniform readonly image2D prev_temporal_light_poly_2;
layout(set = 0, binding = 35, rgba16f) uniform writeonly image2D out_temporal_light_poly_3;
layout(set = 0, binding = 36, rgba16f) uniform readonly image2D prev_temporal_light_poly_3;
layout(set = 0, binding = 37, rgba16f) uniform writeonly image2D out_temporal_light_poly_4;
layout(set = 0, binding = 38, rgba16f) uniform readonly image2D prev_temporal_light_poly_4;
layout(set = 0, binding = 39, rgba16f) uniform writeonly image2D out_temporal_light_poly_5;
layout(set = 0, binding = 40, rgba16f) uniform readonly image2D prev_temporal_light_poly_5;
layout(set = 0, binding = 30, std430) readonly buffer ModelHeaders { ModelHeader a[]; } model_headers;
layout(set = 0, binding = 31, std430) readonly buffer Kusochki { Kusok a[]; } kusochki;
layout(set = 0, binding = 32, std430) readonly buffer Indices { uint16_t a[]; } indices;
layout(set = 0, binding = 33, std430) readonly buffer Vertices { Vertex a[]; } vertices;

#define out_temporal_0 out_temporal_light_poly_0
#define prev_temporal_0 prev_temporal_light_poly_0
#define out_temporal_1 out_temporal_light_poly_1
#define prev_temporal_1 prev_temporal_light_poly_1
#define out_temporal_2 out_temporal_light_poly_2
#define prev_temporal_2 prev_temporal_light_poly_2
#define out_temporal_3 out_temporal_light_poly_3
#define prev_temporal_3 prev_temporal_light_poly_3
#define out_temporal_4 out_temporal_light_poly_4
#define prev_temporal_4 prev_temporal_light_poly_4
#define out_temporal_5 out_temporal_light_poly_5
#define prev_temporal_5 prev_temporal_light_poly_5
#define out_temporal_normal_roughness out_temporal_light_poly_normal_roughness
#define prev_temporal_normal_roughness prev_temporal_light_poly_normal_roughness
#define out_confidence out_light_polygon_confidence

#define RAY_QUERY
#define LIGHT_POLYGON 1
#include "ray_light_direct.glsl"


