#version 460 core
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_ray_query: require

#define SPARTIAL_RECONSTRUCTION_RADIUS 11.
#define SPECULAR_INPUT_IMAGE indirect_specular
#define SPECULAR_OUTPUT_IMAGE out_indirect_specular_reconstructed_pass1

#include "spartial_reconstruction.glsl"
