#version 460 core
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_ray_query: require

#define SPATIAL_RECONSTRUCTION_RADIUS 5.
#define SPECULAR_INPUT_IMAGE indirect_specular_reconstructed_pass1
#define SPECULAR_OUTPUT_IMAGE out_indirect_specular_reconstructed
#define SPATIAL_RECONSTRUCTION_INPUT_RAY_LENGTH(pix) imageLoad(indirect_specular_reconstructed_pass1, pix).a
#define SPATIAL_RECONSTRUCTION_FINAL_PASS 1

#include "spatial_reconstruction.glsl"
